# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='Blank', max_length=100)),
                ('lastName', models.CharField(default='Blank', max_length=100)),
                ('phoneNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('password', models.CharField(blank=True, max_length=1000)),
                ('address', models.TextField()),
                ('joiningDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNo', models.CharField(max_length=200)),
                ('IFSCCode', models.CharField(max_length=200)),
                ('accountHolderName', models.CharField(max_length=100)),
                ('bankName', models.CharField(max_length=200)),
                ('branchName', models.CharField(default='Blank', max_length=200)),
                ('accountType', models.BooleanField()),
                ('panNo', models.CharField(default='Blank', max_length=200)),
                ('aadhaarNo', models.CharField(default='Blank', max_length=200)),
                ('panCard', models.BinaryField(default='Blank')),
                ('aadhaarCard', models.BinaryField(default='Blank')),
                ('photo', models.BinaryField(default='Blank')),
                ('userId', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='customer.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponserId', models.CharField(max_length=10)),
                ('parentId', models.CharField(max_length=10)),
                ('productId', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('userId', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='customer.User')),
            ],
        ),
    ]
